KAKAO_REST_API_KEY = "1162f8cf4ddb4854b34fa856ff54ed81"
KAKAO_JAVASCRIPT_KEY = "1ef02e48d8a64c2921eba7b1004af540"

NAVER_CLIENT_ID = "yZ2Tgs_cAgLUwRalNdwy"
NAVER_CLIENT_SECRET = "pLpsWbsH6H"

[mysql]
user = "car1_user"
password = "Team3Car1"
host = "127.0.0.1"
port = 3306
database = "car1_db"